### ISSUE TITLE
USE_OPENGL not respected consistently

### ISSUE THREAD

**Issue by drew-parsons** [OpenChemistry/avogadrolibs#810]
**Avogadro version: 1.95.1**
 - Avogadrolibs: 1.95.1
 - Qt: 5.15.2

**Desktop version:**
 - OS: Debian GNU/Linux 
 - Version: debian unstable (linux 5.14.9-2)
 - Compiler: g++ 10.3.0

**Describe the bug**
CMakeLists.txt has an option to switch off OpenGL support, USE_OPENGL

It doesn't seem to be consistently respected, though.  avogadro/qtplugins/overlayaxes/CMakeLists.txt for instance has `find_package(OpenGL REQUIRED)` with no `if(USE_OPENGL)` guard.

This is a problem for systems where Qt/OpenGL support is broken, ARM (armel, armhf) in particular, see
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=798408
and
https://buildd.debian.org/status/fetch.php?pkg=avogadrolibs&arch=armel&ver=1.95.1-2&stamp=1633430574&raw=0
https://buildd.debian.org/status/fetch.php?pkg=avogadrolibs&arch=armhf&ver=1.95.1-2&stamp=1633431828&raw=0

It doesn't look like the Qt/GL incompatibility on ARM is going to be fixed any time soon (maybe it'll better in Qt6 with its new Qt Platform Abstraction. Not certain yet).

So the best thing for ARM builds would be to set USE_OPENGL=OFF, but then this bug gets in the way.

**Comment by drew-parsons** [comment]
overlayaxes seems to have the only rogue instance of `find_package(OpenGL REQUIRED)` which could be guarded by `if(USE_OPENGL) ` in overlayaxes/CMakeLists.txt.

But even then there are other second order dependencies, e.g. with `USE_OPENGL=OFF` vanderwaalsao emits
```
In file included from /projects/avogadrolibs/avogadro/rendering/ambientocclusionspheregeometry.h:21,
                 from /projects/avogadrolibs/avogadro/qtplugins/vanderwaalsao/vanderwaalsao.cpp:22:
/projects/avogadrolibs/avogadro/rendering/drawable.h:20:10: fatal error: avogadrorenderingexport.h: No such file or directory
   20 | #include "avogadrorenderingexport.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by drew-parsons** [comment]
As far as the ARM build error goes, it's triggered by including glwidget.h in qtplugins/overlayaxes/overlayaxes.cpp.  This was introduced in commit 97d16609d for 1.95.1, which would be why arm previously built successfully.

**Comment by ghutchis** [comment]
Yes, there were changes to that code - and the GitHub build servers don't have many platforms.

Should be a fairly easy fix.

**Comment by drew-parsons** [comment]
The arm builds do succeed if I simply skip the overlayaxes plugin.

**Comment by ghutchis** [comment]
I'm coming back to this.. I guess my question is what the code should do if USE_OPENGL=FALSE .. considering it's an OpenGL rendering code.

It's useful perhaps for the Python wheels but the GUI seems like it's pretty useless.

**Comment by drew-parsons** [comment]
The problem only seems to be affecting the overlayaxes plugin. The rest of it runs fine, or least the builds finish successfully, with the patch
```
Index: avogadrolibs/CMakeLists.txt
===================================================================
--- avogadrolibs.orig/CMakeLists.txt    2021-08-30 00:44:31.977195825 +0200
+++ avogadrolibs/CMakeLists.txt 2021-10-09 02:45:59.308193466 +0200
@@ -60,6 +60,7 @@
 option(USE_MMTF "Enable optional features using mmtf" ON)
 option(USE_PROTOCALL "Enable libraries that use ProtoCall" OFF)
 option(USE_PYTHON "Use Python to wrap some of our API" OFF)
+option(USE_OVERLAYAXES "Enable OverlayAxes plugin" ON)

 add_subdirectory(utilities)
 add_subdirectory(thirdparty)
Index: avogadrolibs/avogadro/qtplugins/CMakeLists.txt
===================================================================
--- avogadrolibs.orig/avogadro/qtplugins/CMakeLists.txt 2021-10-09 02:43:02.639301456 +0200
+++ avogadrolibs/avogadro/qtplugins/CMakeLists.txt      2021-10-09 02:44:43.791810046 +0200
@@ -163,7 +163,9 @@
 add_subdirectory(wireframe)
 add_subdirectory(force)
 add_subdirectory(meshes)
-add_subdirectory(overlayaxes)
+if (USE_OVERLAYAXES)
+  add_subdirectory(overlayaxes)
+endif()
 add_subdirectory(vanderwaalsao)
 if (USE_PROTOCALL)
   add_subdirectory(clientserver)
```

**Comment by StefanBruens** [comment]
The overlayaxes plugin is still broken on ARM when Qt use build with GLES instead of Desktop OpenGL:
```
[  331s] In file included from /usr/include/qt5/QtGui/qopengl.h:105:0,
[  331s]                  from /usr/include/qt5/QtWidgets/qopenglwidget.h:49,
[  331s]                  from /usr/include/qt5/QtWidgets/QOpenGLWidget:1,
[  331s]                  from /home/abuild/rpmbuild/BUILD/avogadrolibs-1.97.0/avogadro/qtopengl/glwidget.h:15,
[  331s]                  from /home/abuild/rpmbuild/BUILD/avogadrolibs-1.97.0/avogadro/qtplugins/overlayaxes/overlayaxes.cpp:14:
[  331s] /usr/include/GLES3/gl32.h:1819:187: error: 'void __glewTexStorage3DMultisample(GLenum, GLsizei, GLenum, GLsizei, GLsizei, GLsizei, GLboolean)' redeclared as different kind of symbol
[  331s]  GL_APICALL void GL_APIENTRY glTexStorage3DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations);
[  331s]                                                                                                                                                                                            ^
[  331s] In file included from /home/abuild/rpmbuild/BUILD/avogadrolibs-1.97.0/avogadro/rendering/avogadrogl.h:15:0,
[  331s]                  from /home/abuild/rpmbuild/BUILD/avogadrolibs-1.97.0/avogadro/qtplugins/overlayaxes/overlayaxes.cpp:8:
[  331s] /usr/include/GL/glew.h:20900:50: note: previous declaration 'void (* __glewTexStorage3DMultisample)(GLenum, GLsizei, GLenum, GLsizei, GLsizei, GLsizei, GLboolean)'
[  331s]  GLEW_FUN_EXPORT PFNGLTEXSTORAGE3DMULTISAMPLEPROC __glewTexStorage3DMultisample;
[  331s]                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by StefanBruens** [comment]
Definitions from glew.h:
```
#   define GLEWAPI extern __attribute__ ((visibility("default"))) 
...
#ifndef GLAPIENTRY
#define GLAPIENTRY
#endif

#define GLEW_FUN_EXPORT GLEWAPI
...
typedef void (GLAPIENTRY * PFNGLTEXSTORAGE3DMULTISAMPLEPROC) (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations);
...

**Comment by ghutchis** [comment]
I kinda wish you had posted this as a new issue, because it's not about USE_OPENGL, but about compiling on ARM with GLES. 

In any case it seems like the real solution is to migrate from GLEW to https://glbinding.org
